### PR TITLE
Add PWA support

### PR DESCRIPTION
**Pull request by RobertRR11**
WIP because of various things missing. Just wanted to create this pull request to work on it tomorrow.
Todo:
- [x] HTML meta tags
- [x] various icon sizes
- [x] more data in app manifest

### CODE REVIEW

**Comment by RobertRR11** [comment]
forgot to mention #9

**Comment by JackDotJS** [comment]
> * [ ] various icon sizes and monochrome icon

i can handle making new sets of app icons x) i've been wanting to update the design anyway, the current icon is *years* old now

**Comment by JackDotJS** [comment]
do you still need a monochrome icon btw?

**Comment by RobertRR11** [comment]
I can't verify if this is still accurate, but from what I heard, safari uses monochrome SVG icons for tabs, idk if we need this
image

**Comment by JackDotJS** [comment]
i probably should've taken a closer look at this 😅 found a couple issues almost immediately after merging

thank you for the contribution regardless!!!!

**Pull request merged**
