### PR TITLE
(WIP) version search

### LINKED ISSUE #12: add version search
allows users to use text search for the massive list of mc versions they might have installed. might also experiment with using string similarity for a less strict search algorithm.

will 100000000% be needed if #8 gets implemented

### PR DESCRIPTION
**Pull request by RobertRR11**
To be honest I actually have no clue how typescript works
- [x] version fetching
- [x] version filters
- [ ] version search (duh)
- [ ] fallback for version fetching (maybe hardcoded json file?)
- [ ] getting rid of flickering when updating version list

### CODE REVIEW

**Comment by JackDotJS** [comment]
> * [ ] fallback for version fetching (maybe hardcoded json file?)
> * [ ] getting rid of flickering when updating version list

can u elaborate on these?

**Comment by RobertRR11** [comment]
> fallback for version fetching (maybe hardcoded json file?)

For when Mojang API is down or any other network issue

> getting rid of flickering when updating version list

Right now when you filter versions, the whole list gets removed and added again, which shifts the whole page for a very short time. This could probably be solved by just making the list a fixed height

**Comment by JackDotJS** [comment]
> For when Mojang API is down or any other network issue

shouldn't we just list what versions the user has installed? assuming we're sticking with local files only for now

> Right now when you filter versions, the whole list gets removed and added again, which shifts the whole page for a very short time. This could probably be solved by just making the list a fixed height

the list should already be a fixed height. otherwise, adding more items would extend the entire page instead of showing a scroll bar x)

i can't imagine why the whole page would shift if we're changing elements within an overflow element...

**Comment by RobertRR11** [comment]
> the list should already be a fixed height.

The list only has a max height. While the list elements are removed for the short amount of time, the list will get smaller than the max height and shift the page

**Comment by JackDotJS** [comment]
i-

image

# WHY THE FUCK DID I MAKE IT A MAX HEIGHT.

**Pull request closed without merging**
